# Generated by Django 3.1.6 on 2021-02-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_feeding'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeding',
            new_name='Meal',
        ),
    ]
