# Generated by Django 3.1.6 on 2021-02-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210206_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=250)),
                ('photo_url', models.CharField(max_length=250)),
                ('blog_name', models.CharField(max_length=100)),
            ],
        ),
    ]
