# Generated by Django 3.1.6 on 2021-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipes',
            field=models.ManyToManyField(to='main_app.Recipe'),
        ),
    ]
