# Generated by Django 3.1.6 on 2021-02-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_meal_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
