# Generated by Django 3.1.6 on 2021-02-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-id']},
        ),
    ]
